"""followers

Revision ID: 766aaa541154
Revises: 01bb3c113ad9
Create Date: 2020-07-22 21:08:06.588497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766aaa541154'
down_revision = '01bb3c113ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
